eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/,http://localhost:8890/eureka/
  instance:
    #自定义服务名称信息
    instance-id: service-feign-8765
    #访问路径可以显示IP地址
    prefer-ip-address: true    
server:
  port: 8765
  #设置tomcat连接数为50个，测试雪崩效应
  tomcat:
    max-threads: 50
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  # <delimit>$</delimit>中设置的符号
  build.artifactId: $project.artifactId$
  build.version: $project.version$          
spring:
  application:
    name: service-order-feign
feign:
   hystrix:
     enabled: true
###超时时间
hystrix:
   command: 
     default: 
       execution: 
        isolation:
         thread: 
          timeoutInMilliseconds: 4000

