eureka:
 client:
  serviceUrl:
    defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/,http://localhost:8890/eureka/
server:
 port: 8763
spring:
 application:
  name: service-member